from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rebootroute.config import ensure_directories, load_config
from rebootroute.data.mock_data import _write_csv_atomic
from rebootroute.data.official_sources import fetch_all_official_resources
from rebootroute.data.validation import validate_resources


def write_resource_audit(resources, path: Path) -> None:
    suspicious_pattern = r"入口|公式|curated|example\.com|RebootRoute official"
    visible = resources[["name", "description", "source_name", "official_title", "official_summary"]].astype(str).agg(" ".join, axis=1)
    suspicious_count = int(visible.str.contains(suspicious_pattern, case=False, regex=True).sum())
    lines = [
        "# Official Resource Audit",
        "",
        "This report is generated by `scripts/fetch_official_resources.py` after fetching public official pages.",
        "",
        f"- Rows: {len(resources)}",
        f"- Source kinds: {resources['source_kind'].value_counts().to_dict()}",
        f"- Resource types: {resources['resource_type'].value_counts().to_dict()}",
        f"- Source names: {resources['source_name'].value_counts().to_dict()}",
        f"- Checked at min: {resources['source_checked_at'].min()}",
        f"- Checked at max: {resources['source_checked_at'].max()}",
        f"- Missing source URL: {int(resources['source_url'].isna().sum())}",
        f"- Missing detail URL: {int(resources['detail_url'].isna().sum())}",
        f"- Suspicious visible text rows: {suspicious_count}",
        "",
        "Official fields and RebootRoute-derived fields are separated in `sample_resources.csv`: official title/summary/period/place/source fields come from the source pages; burden, tags, duration, and recommendation wording are derived metadata.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    cfg = load_config()
    ensure_directories(cfg)
    resources = fetch_all_official_resources()
    if resources.empty:
        raise RuntimeError("No official resources were fetched. Check network access and official site availability.")
    resources = validate_resources(resources)
    path = cfg.raw_data_dir / "sample_resources.csv"
    _write_csv_atomic(resources, path)
    audit_path = cfg.reports_dir / "resource_audit.md"
    write_resource_audit(resources, audit_path)
    summary = {
        "path": str(path),
        "audit": str(audit_path),
        "rows": len(resources),
        "source_kind": resources["source_kind"].value_counts().to_dict(),
        "resource_type": resources["resource_type"].value_counts().to_dict(),
        "checked_at_min": str(resources["source_checked_at"].min()),
        "checked_at_max": str(resources["source_checked_at"].max()),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
